### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by nyatindopatrick** [kelibst/the-next-web-clone#2]
Feel free to leave any comments.

**Comment by dili021** [comment]
Just some random details I noticed:
-live link not working
-search icon (navbar) should disappear on phone screen
-only the third image of the first grid (top of page) is resizing when you drag the screen
-"latest funding rounds" breaks over the grid above it on medium screen size (check it at 768px)

**Comment by Kyle-Law** [comment]
Great Job @nyatindopatrick ! Here are some feedbacks from me:
![image](https://user-images.githubusercontent.com/55923773/74128870-2b259c80-4c19-11ea-9ce2-4f0560618d4c.png)
- The wordings inside the main header overflow for smaller sizes as shown in the pic above.

![image](https://user-images.githubusercontent.com/55923773/74129018-8788bc00-4c19-11ea-822d-2dd7e504d53e.png)
- Latest Funding title overflow at smaller screen sizes.
- There shall be some margin between items of the latest news.

![image](https://user-images.githubusercontent.com/55923773/74129120-bef76880-4c19-11ea-9bb6-3e5845c9eb6d.png)
- At the smaller screens, the latest deals items are presented in 2 columns with smaller images as shown below: 
![image](https://user-images.githubusercontent.com/55923773/74129410-77bda780-4c1a-11ea-860a-3665eb8dac2e.png)

**Comment by patriciachrysy** [comment]
Good job @nyatindopatrick !!! However, there are still a few things that need to b fixed:
- the text in the gradient box go out of their boxes
- the logo in the red box is too small
- There are some odd text in the 'Podium', 'Insight' and 'Launch' article. 
- under 1024px screen size, the logo must disappear from the red box and appear in the nav-bar
- under 767px screen size, there has to be some space between the latest news boxes
- The latest funding round section is moving out of its bounds for this same screen size
- review the disposition of the latest deals boxes at this same screen size too
- the footer logo nav is not wrapping as it's supposed to
Apart from that, good job!

**Comment by nyatindopatrick** [comment]
Thanks for the comments. They were really helpful.
